// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SvadbeniSalon.Database;

namespace SvadbeniSalon.Database.Migrations
{
    [DbContext(typeof(LocalContext))]
    [Migration("20210322215921_MeniArtikal")]
    partial class MeniArtikal
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Artikal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 22, 21, 59, 20, 976, DateTimeKind.Utc).AddTicks(3484));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Dekoracija", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 22, 21, 59, 20, 975, DateTimeKind.Utc).AddTicks(8329));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Dekoracije");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Korisnik", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 22, 21, 59, 20, 955, DateTimeKind.Utc).AddTicks(9416));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Meni", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 22, 21, 59, 20, 976, DateTimeKind.Utc).AddTicks(7555));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Meniji");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.MeniArtikal", b =>
                {
                    b.Property<long>("MeniId")
                        .HasColumnType("bigint");

                    b.Property<long>("ArtikalId")
                        .HasColumnType("bigint");

                    b.HasKey("MeniId", "ArtikalId");

                    b.HasIndex("ArtikalId");

                    b.ToTable("MeniArtikli");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Muzicar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 22, 21, 59, 20, 966, DateTimeKind.Utc).AddTicks(2927));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Muzicari");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.MuzicarZanr", b =>
                {
                    b.Property<long>("MuzicarId")
                        .HasColumnType("bigint");

                    b.Property<long>("ZanrId")
                        .HasColumnType("bigint");

                    b.HasKey("MuzicarId", "ZanrId");

                    b.HasIndex("ZanrId");

                    b.ToTable("MuzicarZanrovi");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Zanr", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 22, 21, 59, 20, 966, DateTimeKind.Utc).AddTicks(5571));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.MeniArtikal", b =>
                {
                    b.HasOne("SvadbeniSalon.Database.Models.Artikal", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Database.Models.Meni", "Meni")
                        .WithMany("Artikli")
                        .HasForeignKey("MeniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.MuzicarZanr", b =>
                {
                    b.HasOne("SvadbeniSalon.Database.Models.Muzicar", "Muzicar")
                        .WithMany("Zanrovi")
                        .HasForeignKey("MuzicarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Database.Models.Zanr", "Zanr")
                        .WithMany()
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muzicar");

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Meni", b =>
                {
                    b.Navigation("Artikli");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Muzicar", b =>
                {
                    b.Navigation("Zanrovi");
                });
#pragma warning restore 612, 618
        }
    }
}
