// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SvadbeniSalon.Database;

namespace SvadbeniSalon.Database.Migrations
{
    [DbContext(typeof(LocalContext))]
    partial class LocalContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Artikal", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 29, 19, 22, 43, 843, DateTimeKind.Utc).AddTicks(1911));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Artikli");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Dekoracija", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 29, 19, 22, 43, 842, DateTimeKind.Utc).AddTicks(9334));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Dekoracije");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.DekoracijaPonuda", b =>
                {
                    b.Property<long>("PonudaId")
                        .HasColumnType("bigint");

                    b.Property<long>("DekoracijaId")
                        .HasColumnType("bigint");

                    b.HasKey("PonudaId", "DekoracijaId");

                    b.HasIndex("DekoracijaId");

                    b.ToTable("DekoracijaPonuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Korisnik", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 29, 19, 22, 43, 824, DateTimeKind.Utc).AddTicks(6190));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Uloga")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Meni", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 29, 19, 22, 43, 843, DateTimeKind.Utc).AddTicks(4358));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Meniji");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.MeniArtikal", b =>
                {
                    b.Property<long>("MeniId")
                        .HasColumnType("bigint");

                    b.Property<long>("ArtikalId")
                        .HasColumnType("bigint");

                    b.HasKey("MeniId", "ArtikalId");

                    b.HasIndex("ArtikalId");

                    b.ToTable("MeniArtikli");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Muzicar", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 29, 19, 22, 43, 835, DateTimeKind.Utc).AddTicks(3207));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Muzicari");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.MuzicarZanr", b =>
                {
                    b.Property<long>("MuzicarId")
                        .HasColumnType("bigint");

                    b.Property<long>("ZanrId")
                        .HasColumnType("bigint");

                    b.HasKey("MuzicarId", "ZanrId");

                    b.HasIndex("ZanrId");

                    b.ToTable("MuzicarZanrovi");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.MuzicariPonuda", b =>
                {
                    b.Property<long>("PonudaId")
                        .HasColumnType("bigint");

                    b.Property<long>("MuzicarId")
                        .HasColumnType("bigint");

                    b.HasKey("PonudaId", "MuzicarId");

                    b.HasIndex("MuzicarId");

                    b.ToTable("MuzicarDekoracija");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Ponuda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 29, 19, 22, 43, 843, DateTimeKind.Utc).AddTicks(6513));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("MeniId")
                        .HasColumnType("bigint");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeniId");

                    b.ToTable("Ponude");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Zanr", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2021, 3, 29, 19, 22, 43, 835, DateTimeKind.Utc).AddTicks(6361));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.DekoracijaPonuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Database.Models.Dekoracija", "Dekoracija")
                        .WithMany()
                        .HasForeignKey("DekoracijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Database.Models.Ponuda", "Ponuda")
                        .WithMany("DekoracijePonuda")
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dekoracija");

                    b.Navigation("Ponuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.MeniArtikal", b =>
                {
                    b.HasOne("SvadbeniSalon.Database.Models.Artikal", "Artikal")
                        .WithMany()
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Database.Models.Meni", "Meni")
                        .WithMany("Artikli")
                        .HasForeignKey("MeniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.MuzicarZanr", b =>
                {
                    b.HasOne("SvadbeniSalon.Database.Models.Muzicar", "Muzicar")
                        .WithMany("Zanrovi")
                        .HasForeignKey("MuzicarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Database.Models.Zanr", "Zanr")
                        .WithMany()
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muzicar");

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.MuzicariPonuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Database.Models.Muzicar", "Muzicar")
                        .WithMany()
                        .HasForeignKey("MuzicarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Database.Models.Ponuda", "Ponuda")
                        .WithMany("MuzicariPonuda")
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muzicar");

                    b.Navigation("Ponuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Ponuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Database.Models.Meni", "Meni")
                        .WithMany()
                        .HasForeignKey("MeniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Meni", b =>
                {
                    b.Navigation("Artikli");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Muzicar", b =>
                {
                    b.Navigation("Zanrovi");
                });

            modelBuilder.Entity("SvadbeniSalon.Database.Models.Ponuda", b =>
                {
                    b.Navigation("DekoracijePonuda");

                    b.Navigation("MuzicariPonuda");
                });
#pragma warning restore 612, 618
        }
    }
}
