// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SvadbeniSalon.Services.Database;

#nullable disable

namespace SvadbeniSalon.Services.Migrations
{
    [DbContext(typeof(SvadbeniSalonDbContext))]
    [Migration("20260723120232_AddPasswordResetTokens")]
    partial class AddPasswordResetTokens
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Artikal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Artikli");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 15m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Teleća pršuta",
                            Tip = 1
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 18m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Pileći file",
                            Tip = 1
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 25m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Vino crno",
                            Tip = 2
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 5m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Sok od narandže",
                            Tip = 2
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Dekoracija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Dekoracije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 500m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Cvjetna dekoracija",
                            Opis = "Bijeli ruže i hortenzije"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 800m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Zlatna dekoracija",
                            Opis = "Luksuzni zlatni detalji"
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 350m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Rustik dekoracija",
                            Opis = "Prirodni drveni elementi"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DekoracijaPonuda", b =>
                {
                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int>("DekoracijaId")
                        .HasColumnType("int");

                    b.HasKey("PonudaId", "DekoracijaId");

                    b.HasIndex("DekoracijaId");

                    b.ToTable("DekoracijaPonuda");

                    b.HasData(
                        new
                        {
                            PonudaId = 1,
                            DekoracijaId = 2
                        },
                        new
                        {
                            PonudaId = 2,
                            DekoracijaId = 1
                        },
                        new
                        {
                            PonudaId = 3,
                            DekoracijaId = 3
                        },
                        new
                        {
                            PonudaId = 4,
                            DekoracijaId = 1
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DnevniSastanak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumSastanka")
                        .HasColumnType("datetime2");

                    b.Property<string>("KontaktIme")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DnevniSastanci");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Meni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Meniji");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 35m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Klasični meni",
                            Opis = "Tradicionalni svadbeni meni"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 55m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Premium meni",
                            Opis = "Premium jela i pića"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MeniArtikal", b =>
                {
                    b.Property<int>("MeniId")
                        .HasColumnType("int");

                    b.Property<int>("ArtikalId")
                        .HasColumnType("int");

                    b.HasKey("MeniId", "ArtikalId");

                    b.HasIndex("ArtikalId");

                    b.ToTable("MeniArtikli");

                    b.HasData(
                        new
                        {
                            MeniId = 1,
                            ArtikalId = 1
                        },
                        new
                        {
                            MeniId = 1,
                            ArtikalId = 3
                        },
                        new
                        {
                            MeniId = 2,
                            ArtikalId = 2
                        },
                        new
                        {
                            MeniId = 2,
                            ArtikalId = 4
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Muzicar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Muzicari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Michael Jackson",
                            Opis = "Pop legenda"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "The Beatles",
                            Opis = "Rock klasici"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Pjotr Iljič Čajkovski",
                            Opis = "Balet muzika"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarPonuda", b =>
                {
                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int>("MuzicarId")
                        .HasColumnType("int");

                    b.HasKey("PonudaId", "MuzicarId");

                    b.HasIndex("MuzicarId");

                    b.ToTable("MuzicarPonuda");

                    b.HasData(
                        new
                        {
                            PonudaId = 1,
                            MuzicarId = 1
                        },
                        new
                        {
                            PonudaId = 1,
                            MuzicarId = 2
                        },
                        new
                        {
                            PonudaId = 2,
                            MuzicarId = 2
                        },
                        new
                        {
                            PonudaId = 3,
                            MuzicarId = 3
                        },
                        new
                        {
                            PonudaId = 4,
                            MuzicarId = 1
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarZanr", b =>
                {
                    b.Property<int>("MuzicarId")
                        .HasColumnType("int");

                    b.Property<int>("ZanrId")
                        .HasColumnType("int");

                    b.HasKey("MuzicarId", "ZanrId");

                    b.HasIndex("ZanrId");

                    b.ToTable("MuzicarZanrovi");

                    b.HasData(
                        new
                        {
                            MuzicarId = 1,
                            ZanrId = 1
                        },
                        new
                        {
                            MuzicarId = 2,
                            ZanrId = 2
                        },
                        new
                        {
                            MuzicarId = 3,
                            ZanrId = 3
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Code");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Ponuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MeniId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeniId");

                    b.ToTable("Ponude");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 15000m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 2,
                            Naziv = "Gold paket",
                            Opis = "Luksuzni paket sa premium menijem i zlatnom dekoracijom"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 10000m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 1,
                            Naziv = "Silver paket",
                            Opis = "Elegantan paket sa klasičnim menijem"
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 7000m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 1,
                            Naziv = "Bronze paket",
                            Opis = "Osnovni paket za manje proslave"
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 8500m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 1,
                            Naziv = "Regular paket",
                            Opis = "Standardni paket sa cvjetnom dekoracijom"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Racun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KreiraoUserId")
                        .HasColumnType("int");

                    b.Property<int>("SvadbaId")
                        .HasColumnType("int");

                    b.Property<decimal>("UkupanIznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UplaceniIznos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrojRacuna")
                        .IsUnique();

                    b.HasIndex("KreiraoUserId");

                    b.HasIndex("SvadbaId");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Rata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumUplate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SvadbaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SvadbaId");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Recenzija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Komentar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int>("SvadbaId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PonudaId");

                    b.HasIndex("SvadbaId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Recenzije");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Salon employee with access to appointments",
                            IsActive = true,
                            Name = "Zaposlenik"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Svadba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojGostiju")
                        .HasColumnType("int");

                    b.Property<int>("BrojRata")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumSvadbe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Vrijeme")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PonudaId");

                    b.HasIndex("UserId");

                    b.ToTable("Svadbe");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mobile@salon.local",
                            FirstName = "Dalila",
                            IsActive = true,
                            LastName = "Korisnik",
                            PasswordHash = "N5b4vpOtGo4txmR/IoPFNoRg1kY=",
                            PasswordSalt = "JopMnUSdt7Cec4gKUV0rag==",
                            Username = "mobile"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "zaposlenik@salon.local",
                            FirstName = "Zaposlenik",
                            IsActive = true,
                            LastName = "Salon",
                            PasswordHash = "xObgsmDrWZgNlmGJsdxoRS+V/AE=",
                            PasswordSalt = "0k57QETJENx5BkJuK4wtZg==",
                            Username = "zaposlenik"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@salon.local",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "Korisnik",
                            PasswordHash = "qU2ck45AOJU9W8CVxAO89FyOb8M=",
                            PasswordSalt = "65z57pEcbOuw+c9Ma3X10Q==",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 8
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Zanr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Balet"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Jazz"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Klasična"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Narodna"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Starogradska"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Akustična"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Evergreen"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Naziv = "Elektronska"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DekoracijaPonuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Dekoracija", "Dekoracija")
                        .WithMany("DekoracijePonuda")
                        .HasForeignKey("DekoracijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany("DekoracijePonuda")
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dekoracija");

                    b.Navigation("Ponuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DnevniSastanak", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MeniArtikal", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Artikal", "Artikal")
                        .WithMany("MeniArtikli")
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Meni", "Meni")
                        .WithMany("MeniArtikli")
                        .HasForeignKey("MeniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarPonuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Muzicar", "Muzicar")
                        .WithMany("MuzicariPonuda")
                        .HasForeignKey("MuzicarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany("MuzicariPonuda")
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muzicar");

                    b.Navigation("Ponuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarZanr", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Muzicar", "Muzicar")
                        .WithMany("MuzicarZanrovi")
                        .HasForeignKey("MuzicarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Zanr", "Zanr")
                        .WithMany("MuzicarZanrovi")
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muzicar");

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.PasswordResetToken", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Ponuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Meni", "Meni")
                        .WithMany("Ponude")
                        .HasForeignKey("MeniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Racun", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "KreiraoUser")
                        .WithMany()
                        .HasForeignKey("KreiraoUserId");

                    b.HasOne("SvadbeniSalon.Services.Database.Svadba", "Svadba")
                        .WithMany("Racuni")
                        .HasForeignKey("SvadbaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KreiraoUser");

                    b.Navigation("Svadba");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Rata", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Svadba", "Svadba")
                        .WithMany("Rate")
                        .HasForeignKey("SvadbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Svadba");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Recenzija", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany()
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Svadba", "Svadba")
                        .WithMany()
                        .HasForeignKey("SvadbaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ponuda");

                    b.Navigation("Svadba");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.RefreshToken", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Svadba", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany()
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ponuda");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.UserRole", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Artikal", b =>
                {
                    b.Navigation("MeniArtikli");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Dekoracija", b =>
                {
                    b.Navigation("DekoracijePonuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Meni", b =>
                {
                    b.Navigation("MeniArtikli");

                    b.Navigation("Ponude");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Muzicar", b =>
                {
                    b.Navigation("MuzicarZanrovi");

                    b.Navigation("MuzicariPonuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Ponuda", b =>
                {
                    b.Navigation("DekoracijePonuda");

                    b.Navigation("MuzicariPonuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Svadba", b =>
                {
                    b.Navigation("Racuni");

                    b.Navigation("Rate");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.User", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Zanr", b =>
                {
                    b.Navigation("MuzicarZanrovi");
                });
#pragma warning restore 612, 618
        }
    }
}
