// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SvadbeniSalon.Services.Database;

#nullable disable

namespace SvadbeniSalon.Services.Migrations
{
    [DbContext(typeof(SvadbeniSalonDbContext))]
    [Migration("20260616112655_AddDnevniSastanakGuestAndSlots")]
    partial class AddDnevniSastanakGuestAndSlots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Artikal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Artikli");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 15m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Teleća pršuta",
                            Tip = 1
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 18m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Pileći file",
                            Tip = 1
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 25m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Vino crno",
                            Tip = 2
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 5m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Sok od narandže",
                            Tip = 2
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Base64Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Electronic devices and accessories",
                            IsActive = true,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Desktops, laptops and related hardware",
                            IsActive = true,
                            Name = "Computers",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Smartphones and mobile devices",
                            IsActive = true,
                            Name = "Mobile Phones",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Device accessories and peripherals",
                            IsActive = true,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Cupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Uses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "WELCOME10",
                            CreatedAt = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 10.0,
                            DiscountType = 0,
                            ExpiresAt = new DateTime(2026, 12, 31, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Uses = 0
                        },
                        new
                        {
                            Id = 2,
                            Code = "SPRING15",
                            CreatedAt = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 15.0,
                            DiscountType = 0,
                            ExpiresAt = new DateTime(2026, 6, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Uses = 0
                        },
                        new
                        {
                            Id = 3,
                            Code = "SAVE20",
                            CreatedAt = new DateTime(2026, 5, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DiscountAmount = 20.0,
                            DiscountType = 1,
                            ExpiresAt = new DateTime(2026, 11, 30, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Uses = 0
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Dekoracija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Dekoracije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 500m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Cvjetna dekoracija",
                            Opis = "Bijeli ruže i hortenzije"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 800m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Zlatna dekoracija",
                            Opis = "Luksuzni zlatni detalji"
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 350m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Rustik dekoracija",
                            Opis = "Prirodni drveni elementi"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DekoracijaPonuda", b =>
                {
                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int>("DekoracijaId")
                        .HasColumnType("int");

                    b.HasKey("PonudaId", "DekoracijaId");

                    b.HasIndex("DekoracijaId");

                    b.ToTable("DekoracijaPonuda");

                    b.HasData(
                        new
                        {
                            PonudaId = 1,
                            DekoracijaId = 2
                        },
                        new
                        {
                            PonudaId = 2,
                            DekoracijaId = 1
                        },
                        new
                        {
                            PonudaId = 3,
                            DekoracijaId = 3
                        },
                        new
                        {
                            PonudaId = 4,
                            DekoracijaId = 1
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DnevniSastanak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumSastanka")
                        .HasColumnType("datetime2");

                    b.Property<string>("KontaktIme")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DnevniSastanci");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Meni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Meniji");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 35m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Klasični meni",
                            Opis = "Tradicionalni svadbeni meni"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 55m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Premium meni",
                            Opis = "Premium jela i pića"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MeniArtikal", b =>
                {
                    b.Property<int>("MeniId")
                        .HasColumnType("int");

                    b.Property<int>("ArtikalId")
                        .HasColumnType("int");

                    b.HasKey("MeniId", "ArtikalId");

                    b.HasIndex("ArtikalId");

                    b.ToTable("MeniArtikli");

                    b.HasData(
                        new
                        {
                            MeniId = 1,
                            ArtikalId = 1
                        },
                        new
                        {
                            MeniId = 1,
                            ArtikalId = 3
                        },
                        new
                        {
                            MeniId = 2,
                            ArtikalId = 2
                        },
                        new
                        {
                            MeniId = 2,
                            ArtikalId = 4
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Muzicar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Muzicari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Michael Jackson",
                            Opis = "Pop legenda"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "The Beatles",
                            Opis = "Rock klasici"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Pjotr Iljič Čajkovski",
                            Opis = "Balet muzika"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarPonuda", b =>
                {
                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int>("MuzicarId")
                        .HasColumnType("int");

                    b.HasKey("PonudaId", "MuzicarId");

                    b.HasIndex("MuzicarId");

                    b.ToTable("MuzicarPonuda");

                    b.HasData(
                        new
                        {
                            PonudaId = 1,
                            MuzicarId = 1
                        },
                        new
                        {
                            PonudaId = 1,
                            MuzicarId = 2
                        },
                        new
                        {
                            PonudaId = 2,
                            MuzicarId = 2
                        },
                        new
                        {
                            PonudaId = 3,
                            MuzicarId = 3
                        },
                        new
                        {
                            PonudaId = 4,
                            MuzicarId = 1
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarZanr", b =>
                {
                    b.Property<int>("MuzicarId")
                        .HasColumnType("int");

                    b.Property<int>("ZanrId")
                        .HasColumnType("int");

                    b.HasKey("MuzicarId", "ZanrId");

                    b.HasIndex("ZanrId");

                    b.ToTable("MuzicarZanrovi");

                    b.HasData(
                        new
                        {
                            MuzicarId = 1,
                            ZanrId = 1
                        },
                        new
                        {
                            MuzicarId = 2,
                            ZanrId = 2
                        },
                        new
                        {
                            MuzicarId = 3,
                            ZanrId = 3
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CuponId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ShippingZipCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuponId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Ponuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MeniId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeniId");

                    b.ToTable("Ponude");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 15000m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 2,
                            Naziv = "Gold paket",
                            Opis = "Luksuzni paket sa premium menijem i zlatnom dekoracijom"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 10000m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 1,
                            Naziv = "Silver paket",
                            Opis = "Elegantan paket sa klasičnim menijem"
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 7000m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 1,
                            Naziv = "Bronze paket",
                            Opis = "Osnovni paket za manje proslave"
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 8500m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 1,
                            Naziv = "Regular paket",
                            Opis = "Standardni paket sa cvjetnom dekoracijom"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductState")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("ProductTypeId")
                        .HasColumnType("int");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int?>("UnitOfMeasureId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("UnitOfMeasureId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High-performance laptop suitable for gaming and development",
                            IsActive = true,
                            Name = "Gaming Laptop",
                            Price = 999.99m,
                            ProductState = "DraftProductState",
                            SKU = "LAP-1000",
                            StockQuantity = 10,
                            Weight = 2500m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Latest generation smartphone with advanced camera features",
                            IsActive = true,
                            Name = "Smartphone X",
                            Price = 699.99m,
                            ProductState = "DraftProductState",
                            SKU = "PHN-2000",
                            StockQuantity = 25,
                            Weight = 180m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ergonomic wireless mouse with long battery life",
                            IsActive = true,
                            Name = "Wireless Mouse",
                            Price = 19.99m,
                            ProductState = "DraftProductState",
                            SKU = "MSE-300",
                            StockQuantity = 150,
                            Weight = 100m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "65W USB-C fast charger compatible with laptops and phones",
                            IsActive = true,
                            Name = "USB-C Fast Charger",
                            Price = 29.99m,
                            ProductState = "DraftProductState",
                            SKU = "CHR-400",
                            StockQuantity = 200,
                            Weight = 120m
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "RGB mechanical keyboard with tactile switches",
                            IsActive = true,
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            ProductState = "DraftProductState",
                            SKU = "KEY-500",
                            StockQuantity = 75,
                            Weight = 900m
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Over-ear headphones with active noise cancellation",
                            IsActive = true,
                            Name = "Noise-Cancelling Headphones",
                            Price = 199.99m,
                            ProductState = "DraftProductState",
                            SKU = "HDP-600",
                            StockQuantity = 40,
                            Weight = 350m
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "27-inch 4K UHD monitor with HDR and low response time",
                            IsActive = true,
                            Name = "27\" 4K Monitor",
                            Price = 349.99m,
                            ProductState = "DraftProductState",
                            SKU = "MON-700",
                            StockQuantity = 30,
                            Weight = 4500m
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portable 1TB external SSD with high-speed USB-C connectivity",
                            IsActive = true,
                            Name = "External SSD 1TB",
                            Price = 129.99m,
                            ProductState = "DraftProductState",
                            SKU = "SSD-800",
                            StockQuantity = 60,
                            Weight = 80m
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Full HD webcam with built-in microphone and privacy shutter",
                            IsActive = true,
                            Name = "Webcam Pro 1080p",
                            Price = 59.99m,
                            ProductState = "DraftProductState",
                            SKU = "CAM-900",
                            StockQuantity = 90,
                            Weight = 140m
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact Bluetooth speaker with waterproof design and deep bass",
                            IsActive = true,
                            Name = "Bluetooth Speaker",
                            Price = 49.99m,
                            ProductState = "DraftProductState",
                            SKU = "SPK-1000",
                            StockQuantity = 110,
                            Weight = 620m
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fitness-focused smartwatch with heart-rate tracking and GPS",
                            IsActive = true,
                            Name = "Smartwatch Active",
                            Price = 149.99m,
                            ProductState = "DraftProductState",
                            SKU = "WCH-1100",
                            StockQuantity = 55,
                            Weight = 50m
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable aluminum laptop stand for improved desk ergonomics",
                            IsActive = true,
                            Name = "Laptop Stand Aluminum",
                            Price = 39.99m,
                            ProductState = "DraftProductState",
                            SKU = "STD-1200",
                            StockQuantity = 85,
                            Weight = 750m
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dual-band Wi-Fi 6 router with extended coverage for home networks",
                            IsActive = true,
                            Name = "Wi-Fi 6 Router",
                            Price = 119.99m,
                            ProductState = "DraftProductState",
                            SKU = "RTR-1300",
                            StockQuantity = 45,
                            Weight = 680m
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Digital drawing tablet with pressure-sensitive stylus",
                            IsActive = true,
                            Name = "Graphics Tablet",
                            Price = 79.99m,
                            ProductState = "DraftProductState",
                            SKU = "TAB-1400",
                            StockQuantity = 35,
                            Weight = 420m
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "20000mAh portable power bank with dual USB output",
                            IsActive = true,
                            Name = "Portable Power Bank",
                            Price = 34.99m,
                            ProductState = "DraftProductState",
                            SKU = "PWR-1500",
                            StockQuantity = 130,
                            Weight = 410m
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cat 6 Ethernet cable for reliable high-speed wired networking",
                            IsActive = true,
                            Name = "Ethernet Cable 10m",
                            Price = 12.99m,
                            ProductState = "DraftProductState",
                            SKU = "NET-1600",
                            StockQuantity = 300,
                            Weight = 260m
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "USB-C docking station with HDMI, Ethernet, USB-A, and card reader ports",
                            IsActive = true,
                            Name = "Docking Station",
                            Price = 99.99m,
                            ProductState = "DraftProductState",
                            SKU = "DOC-1700",
                            StockQuantity = 50,
                            Weight = 520m
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable LED desk lamp with touch controls and multiple brightness levels",
                            IsActive = true,
                            Name = "Smart LED Desk Lamp",
                            Price = 44.99m,
                            ProductState = "DraftProductState",
                            SKU = "LMP-1800",
                            StockQuantity = 70,
                            Weight = 850m
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact 4K action camera with waterproof casing and image stabilization",
                            IsActive = true,
                            Name = "Action Camera",
                            Price = 179.99m,
                            ProductState = "DraftProductState",
                            SKU = "ACT-1900",
                            StockQuantity = 28,
                            Weight = 160m
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Standalone virtual reality headset with motion controllers",
                            IsActive = true,
                            Name = "VR Headset",
                            Price = 299.99m,
                            ProductState = "DraftProductState",
                            SKU = "VRH-2000",
                            StockQuantity = 20,
                            Weight = 620m
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Central smart home hub for connecting lights, sensors, and voice assistants",
                            IsActive = true,
                            Name = "Smart Home Hub",
                            Price = 84.99m,
                            ProductState = "DraftProductState",
                            SKU = "HUB-2100",
                            StockQuantity = 42,
                            Weight = 300m
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lightweight fitness tracker with step counting, sleep monitoring, and notifications",
                            IsActive = true,
                            Name = "Fitness Tracker Band",
                            Price = 69.99m,
                            ProductState = "DraftProductState",
                            SKU = "FIT-2200",
                            StockQuantity = 95,
                            Weight = 35m
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Slim wireless charging pad compatible with Qi-enabled smartphones and earbuds",
                            IsActive = true,
                            Name = "Wireless Charging Pad",
                            Price = 24.99m,
                            ProductState = "DraftProductState",
                            SKU = "WCP-2300",
                            StockQuantity = 160,
                            Weight = 110m
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Two-bay network attached storage enclosure for backups and media sharing",
                            IsActive = true,
                            Name = "NAS Storage Enclosure",
                            Price = 229.99m,
                            ProductState = "DraftProductState",
                            SKU = "NAS-2400",
                            StockQuantity = 18,
                            Weight = 1300m
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portable digital voice recorder with noise reduction and long recording time",
                            IsActive = true,
                            Name = "Digital Voice Recorder",
                            Price = 54.99m,
                            ProductState = "DraftProductState",
                            SKU = "REC-2500",
                            StockQuantity = 65,
                            Weight = 90m
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Portable mini projector with HDMI input and built-in speaker",
                            IsActive = true,
                            Name = "Mini Projector",
                            Price = 159.99m,
                            ProductState = "DraftProductState",
                            SKU = "PRJ-2600",
                            StockQuantity = 32,
                            Weight = 950m
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Wi-Fi smart doorbell camera with motion detection and two-way audio",
                            IsActive = true,
                            Name = "Smart Doorbell Camera",
                            Price = 139.99m,
                            ProductState = "DraftProductState",
                            SKU = "DRB-2700",
                            StockQuantity = 38,
                            Weight = 250m
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.ProductCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            ProductId = 6
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ProductId = 7
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tangible products that require shipping",
                            IsActive = true,
                            Name = "Physical"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Intangible products that can be downloaded",
                            IsActive = true,
                            Name = "Digital"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Non-physical products that provide a service",
                            IsActive = true,
                            Name = "Service"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Racun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KreiraoUserId")
                        .HasColumnType("int");

                    b.Property<int>("SvadbaId")
                        .HasColumnType("int");

                    b.Property<decimal>("UkupanIznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UplaceniIznos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrojRacuna")
                        .IsUnique();

                    b.HasIndex("KreiraoUserId");

                    b.HasIndex("SvadbaId");

                    b.ToTable("Racuni");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Rata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumUplate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SvadbaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SvadbaId");

                    b.ToTable("Rate");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Recenzija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Komentar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int>("SvadbaId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PonudaId");

                    b.HasIndex("SvadbaId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Recenzije");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator role with full permissions",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default customer role",
                            IsActive = true,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Salon employee with access to appointments",
                            IsActive = true,
                            Name = "Zaposlenik"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Svadba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojGostiju")
                        .HasColumnType("int");

                    b.Property<int>("BrojRata")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumSvadbe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Vrijeme")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PonudaId");

                    b.HasIndex("UserId");

                    b.ToTable("Svadbe");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.UnitOfMeasure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UnitOfMeasures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "pc",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Name = "Piece"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "kg",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Name = "Kilogram"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "L",
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "",
                            IsActive = true,
                            Name = "Liter"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin1@gmail.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "5kRBQg4Ufcx4hAknG7P9zhfLPvY=",
                            PasswordSalt = "FmvmUwPsJyRRffhNRQvbrA==",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin2@gmail.com",
                            FirstName = "Bob",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "GBoyh1WP+OMgGjqRj6vK6L1+oGc=",
                            PasswordSalt = "0AXpKx6xRp9xM42jCf/PiA==",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin3@gmail.com",
                            FirstName = "Carol",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "x6JHKCTQywdAzTcZxGWFvrKPORM=",
                            PasswordSalt = "IwhTfKQNgyqWfOlTqCDXrg==",
                            Username = "admin3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer1@gmail.com",
                            FirstName = "Dave",
                            IsActive = true,
                            LastName = "Customer",
                            PasswordHash = "E0fA2/f9GZvIRRt/cgqQemG/Cog=",
                            PasswordSalt = "TiJxWTJcd7sBSiWNbhK9Vw==",
                            Username = "customer1"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "customer2@gmail.com",
                            FirstName = "Eve",
                            IsActive = true,
                            LastName = "Customer",
                            PasswordHash = "Ov4LxpWKXXV9dwMYvBgqODdzIt0=",
                            PasswordSalt = "KtWF6g7SemBqs4nVWV4Ziw==",
                            Username = "customer2"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mobile@salon.local",
                            FirstName = "Dalila",
                            IsActive = true,
                            LastName = "Korisnik",
                            PasswordHash = "N5b4vpOtGo4txmR/IoPFNoRg1kY=",
                            PasswordSalt = "JopMnUSdt7Cec4gKUV0rag==",
                            Username = "mobile"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "zaposlenik@salon.local",
                            FirstName = "Zaposlenik",
                            IsActive = true,
                            LastName = "Salon",
                            PasswordHash = "xObgsmDrWZgNlmGJsdxoRS+V/AE=",
                            PasswordSalt = "0k57QETJENx5BkJuK4wtZg==",
                            Username = "zaposlenik"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@salon.local",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "Korisnik",
                            PasswordHash = "qU2ck45AOJU9W8CVxAO89FyOb8M=",
                            PasswordSalt = "65z57pEcbOuw+c9Ma3X10Q==",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateAssigned = new DateTime(2026, 3, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 8
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Zanr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Balet"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Asset", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Product", "Product")
                        .WithMany("Assets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Cart", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.CartItem", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Category", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DekoracijaPonuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Dekoracija", "Dekoracija")
                        .WithMany("DekoracijePonuda")
                        .HasForeignKey("DekoracijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany("DekoracijePonuda")
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dekoracija");

                    b.Navigation("Ponuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DnevniSastanak", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MeniArtikal", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Artikal", "Artikal")
                        .WithMany("MeniArtikli")
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Meni", "Meni")
                        .WithMany("MeniArtikli")
                        .HasForeignKey("MeniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarPonuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Muzicar", "Muzicar")
                        .WithMany("MuzicariPonuda")
                        .HasForeignKey("MuzicarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany("MuzicariPonuda")
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muzicar");

                    b.Navigation("Ponuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarZanr", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Muzicar", "Muzicar")
                        .WithMany("MuzicarZanrovi")
                        .HasForeignKey("MuzicarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Zanr", "Zanr")
                        .WithMany("MuzicarZanrovi")
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muzicar");

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Order", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Cupon", "Cupon")
                        .WithMany("Orders")
                        .HasForeignKey("CuponId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.OrderItem", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Ponuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Meni", "Meni")
                        .WithMany("Ponude")
                        .HasForeignKey("MeniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Product", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId");

                    b.HasOne("SvadbeniSalon.Services.Database.UnitOfMeasure", "UnitOfMeasure")
                        .WithMany("Products")
                        .HasForeignKey("UnitOfMeasureId");

                    b.Navigation("ProductType");

                    b.Navigation("UnitOfMeasure");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.ProductCategory", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.ProductReview", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Order", "Order")
                        .WithMany("ProductReviews")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SvadbeniSalon.Services.Database.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Racun", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "KreiraoUser")
                        .WithMany()
                        .HasForeignKey("KreiraoUserId");

                    b.HasOne("SvadbeniSalon.Services.Database.Svadba", "Svadba")
                        .WithMany("Racuni")
                        .HasForeignKey("SvadbaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KreiraoUser");

                    b.Navigation("Svadba");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Rata", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Svadba", "Svadba")
                        .WithMany("Rate")
                        .HasForeignKey("SvadbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Svadba");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Recenzija", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany()
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Svadba", "Svadba")
                        .WithMany()
                        .HasForeignKey("SvadbaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ponuda");

                    b.Navigation("Svadba");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.RefreshToken", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Svadba", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany()
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ponuda");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.UserRole", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Artikal", b =>
                {
                    b.Navigation("MeniArtikli");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Category", b =>
                {
                    b.Navigation("ChildCategories");

                    b.Navigation("ProductCategories");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Cupon", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Dekoracija", b =>
                {
                    b.Navigation("DekoracijePonuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Meni", b =>
                {
                    b.Navigation("MeniArtikli");

                    b.Navigation("Ponude");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Muzicar", b =>
                {
                    b.Navigation("MuzicarZanrovi");

                    b.Navigation("MuzicariPonuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Order", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("ProductReviews");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Ponuda", b =>
                {
                    b.Navigation("DekoracijePonuda");

                    b.Navigation("MuzicariPonuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Product", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductCategories");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Svadba", b =>
                {
                    b.Navigation("Racuni");

                    b.Navigation("Rate");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.UnitOfMeasure", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Zanr", b =>
                {
                    b.Navigation("MuzicarZanrovi");
                });
#pragma warning restore 612, 618
        }
    }
}
