// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SvadbeniSalon.Services.Database;

#nullable disable

namespace SvadbeniSalon.Services.Migrations
{
    [DbContext(typeof(SvadbeniSalonDbContext))]
    [Migration("20261008123305_SyncRecommenderSeedSnapshot")]
    partial class SyncRecommenderSeedSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Artikal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Artikli");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 15m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Teleća pršuta",
                            Tip = 1
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 18m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Pileći file",
                            Tip = 1
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 25m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Vino crno",
                            Tip = 2
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 5m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Sok od narandže",
                            Tip = 2
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Dekoracija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Dekoracije");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 500m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Cvjetna dekoracija",
                            Opis = "Bijele ruže, hortenzije i svijeće za romantičan ambijent"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 800m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Zlatna dekoracija",
                            Opis = "Luksuzni zlatni detalji, kristalne vase i LED akcenti"
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 350m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Rustik dekoracija",
                            Opis = "Drvo, laneno platno i suho cvijeće za tradicionalni ugođaj"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DekoracijaPonuda", b =>
                {
                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int>("DekoracijaId")
                        .HasColumnType("int");

                    b.HasKey("PonudaId", "DekoracijaId");

                    b.HasIndex("DekoracijaId");

                    b.ToTable("DekoracijaPonuda");

                    b.HasData(
                        new
                        {
                            PonudaId = 1,
                            DekoracijaId = 2
                        },
                        new
                        {
                            PonudaId = 2,
                            DekoracijaId = 1
                        },
                        new
                        {
                            PonudaId = 3,
                            DekoracijaId = 3
                        },
                        new
                        {
                            PonudaId = 4,
                            DekoracijaId = 1
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DnevniSastanak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumSastanka")
                        .HasColumnType("datetime2");

                    b.Property<string>("KontaktIme")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusChangeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusChangedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusChangedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("DnevniSastanci");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSastanka = new DateTime(2025, 8, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            Napomena = "Dogovor oko menija i dekoracije.",
                            Status = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSastanka = new DateTime(2025, 11, 5, 14, 0, 0, 0, DateTimeKind.Utc),
                            Napomena = "Klijent nije mogao doći.",
                            Status = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSastanka = new DateTime(2026, 8, 20, 11, 0, 0, 0, DateTimeKind.Utc),
                            Napomena = "Razgled salona i dogovor detalja.",
                            Status = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSastanka = new DateTime(2026, 9, 1, 9, 30, 0, 0, DateTimeKind.Utc),
                            Napomena = "Čeka se potvrda termina.",
                            Status = 0,
                            UserId = 6
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSastanka = new DateTime(2026, 7, 25, 15, 0, 0, 0, DateTimeKind.Utc),
                            KontaktIme = "Ana Marić",
                            Napomena = "Dogovor telefonom, dolazak izvana.",
                            Status = 0
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Meni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Meniji");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 35m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Klasični meni",
                            Opis = "Tradicionalni svadbeni meni"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 55m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Premium meni",
                            Opis = "Premium jela i pića"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MeniArtikal", b =>
                {
                    b.Property<int>("MeniId")
                        .HasColumnType("int");

                    b.Property<int>("ArtikalId")
                        .HasColumnType("int");

                    b.HasKey("MeniId", "ArtikalId");

                    b.HasIndex("ArtikalId");

                    b.ToTable("MeniArtikli");

                    b.HasData(
                        new
                        {
                            MeniId = 1,
                            ArtikalId = 1
                        },
                        new
                        {
                            MeniId = 1,
                            ArtikalId = 3
                        },
                        new
                        {
                            MeniId = 2,
                            ArtikalId = 2
                        },
                        new
                        {
                            MeniId = 2,
                            ArtikalId = 4
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Muzicar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Muzicari");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Hit Parade Bend",
                            Opis = "Live pop i evergreen hitovi za plesni dio večeri"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Electric Avenue",
                            Opis = "Energičan rock bend za zabavniju svadbenu atmosferu"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Kvartet Armonija",
                            Opis = "Gudački kvartet za ceremoniju i elegantni doček"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Sevdah Ansambl",
                            Opis = "Narodna i starogradska muzika uživo"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Jazz Club Trio",
                            Opis = "Lounge i swing jazz tokom večere"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Duo Tišina",
                            Opis = "Akustični duo za intimne trenutke i evergreen klasike"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarPonuda", b =>
                {
                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int>("MuzicarId")
                        .HasColumnType("int");

                    b.HasKey("PonudaId", "MuzicarId");

                    b.HasIndex("MuzicarId");

                    b.ToTable("MuzicarPonuda");

                    b.HasData(
                        new
                        {
                            PonudaId = 1,
                            MuzicarId = 1
                        },
                        new
                        {
                            PonudaId = 1,
                            MuzicarId = 5
                        },
                        new
                        {
                            PonudaId = 2,
                            MuzicarId = 3
                        },
                        new
                        {
                            PonudaId = 2,
                            MuzicarId = 6
                        },
                        new
                        {
                            PonudaId = 3,
                            MuzicarId = 4
                        },
                        new
                        {
                            PonudaId = 4,
                            MuzicarId = 1
                        },
                        new
                        {
                            PonudaId = 4,
                            MuzicarId = 2
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarZanr", b =>
                {
                    b.Property<int>("MuzicarId")
                        .HasColumnType("int");

                    b.Property<int>("ZanrId")
                        .HasColumnType("int");

                    b.HasKey("MuzicarId", "ZanrId");

                    b.HasIndex("ZanrId");

                    b.ToTable("MuzicarZanrovi");

                    b.HasData(
                        new
                        {
                            MuzicarId = 1,
                            ZanrId = 1
                        },
                        new
                        {
                            MuzicarId = 1,
                            ZanrId = 9
                        },
                        new
                        {
                            MuzicarId = 2,
                            ZanrId = 2
                        },
                        new
                        {
                            MuzicarId = 3,
                            ZanrId = 5
                        },
                        new
                        {
                            MuzicarId = 4,
                            ZanrId = 6
                        },
                        new
                        {
                            MuzicarId = 4,
                            ZanrId = 7
                        },
                        new
                        {
                            MuzicarId = 5,
                            ZanrId = 4
                        },
                        new
                        {
                            MuzicarId = 6,
                            ZanrId = 8
                        },
                        new
                        {
                            MuzicarId = 6,
                            ZanrId = 9
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Notifikacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Kind")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("Notifikacije");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CodeSalt")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpiresAt");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Ponuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MeniId")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeniId");

                    b.ToTable("Ponude");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cijena = 15000m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 2,
                            Naziv = "Gold paket",
                            Opis = "Luksuzna večer: premium meni, zlatna dekoracija, pop/evergreen bend i jazz trio"
                        },
                        new
                        {
                            Id = 2,
                            Cijena = 10000m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 1,
                            Naziv = "Silver paket",
                            Opis = "Elegantna klasika: klasični meni, cvjetna dekoracija, gudači i akustični duo"
                        },
                        new
                        {
                            Id = 3,
                            Cijena = 7000m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 1,
                            Naziv = "Bronze paket",
                            Opis = "Tradicionalna svadba: narodna i starogradska muzika, rustik dekoracija"
                        },
                        new
                        {
                            Id = 4,
                            Cijena = 8500m,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            MeniId = 1,
                            Naziv = "Regular paket",
                            Opis = "Zabavna večer: pop i rock bend, cvjetna dekoracija, klasični meni"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Racun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrojRacuna")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumIzdavanja")
                        .HasColumnType("datetime2");

                    b.Property<int?>("KreiraoUserId")
                        .HasColumnType("int");

                    b.Property<int>("SvadbaId")
                        .HasColumnType("int");

                    b.Property<decimal>("UkupanIznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UplaceniIznos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BrojRacuna")
                        .IsUnique();

                    b.HasIndex("KreiraoUserId");

                    b.HasIndex("SvadbaId");

                    b.ToTable("Racuni");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            BrojRacuna = "RAC-2025-001",
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumIzdavanja = new DateTime(2025, 9, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            KreiraoUserId = 8,
                            SvadbaId = 101,
                            UkupanIznos = 10000m,
                            UplaceniIznos = 10000m
                        },
                        new
                        {
                            Id = 102,
                            BrojRacuna = "RAC-2026-002",
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumIzdavanja = new DateTime(2026, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            KreiraoUserId = 7,
                            SvadbaId = 102,
                            UkupanIznos = 15000m,
                            UplaceniIznos = 5000m
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Rata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumUplate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Iznos")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SvadbaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SvadbaId");

                    b.ToTable("Rate");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumUplate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Iznos = 5000m,
                            SvadbaId = 101
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumUplate = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Iznos = 5000m,
                            SvadbaId = 101
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumUplate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Iznos = 5000m,
                            SvadbaId = 102
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Recenzija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Komentar")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Ocjena")
                        .HasColumnType("int");

                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int?>("SvadbaId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PonudaId");

                    b.HasIndex("SvadbaId")
                        .IsUnique()
                        .HasFilter("[SvadbaId] IS NOT NULL");

                    b.HasIndex("UserId", "PonudaId")
                        .IsUnique();

                    b.ToTable("Recenzije");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Komentar = "Sve je bilo predivno. Osoblje ljubazno, meni odličan, a dekoracija baš kako smo zamislili.",
                            Ocjena = 5,
                            PonudaId = 2,
                            SvadbaId = 101,
                            UserId = 6
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Komentar = "Sevdah Ansambl je napravio atmosferu — baš onako kako smo htjeli za tradicionalnu svadbu.",
                            Ocjena = 5,
                            PonudaId = 3,
                            SvadbaId = 104,
                            UserId = 9
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Komentar = "Kvartet Armonija i Duo Tišina — elegantno od dočeka do večere.",
                            Ocjena = 5,
                            PonudaId = 2,
                            SvadbaId = 105,
                            UserId = 10
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Komentar = "Gosti su plesali cijelu noć uz pop i rock bend.",
                            Ocjena = 5,
                            PonudaId = 4,
                            SvadbaId = 106,
                            UserId = 11
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Komentar = "Gold paket je luksuzan; jazz trio tokom večere je bio hit.",
                            Ocjena = 4,
                            PonudaId = 1,
                            SvadbaId = 107,
                            UserId = 11
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Komentar = "Elegantno, ali nama više odgovara narodni ugođaj.",
                            Ocjena = 3,
                            PonudaId = 2,
                            UserId = 9
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrator role with full permissions",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default customer role",
                            IsActive = true,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Salon employee with access to appointments",
                            IsActive = true,
                            Name = "Zaposlenik"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Svadba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrojGostiju")
                        .HasColumnType("int");

                    b.Property<int>("BrojRata")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumSvadbe")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DogovorenaCijena")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Napomena")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PonudaId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusChangeReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StatusChangedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Vrijeme")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("PonudaId");

                    b.HasIndex("StatusChangedByUserId");

                    b.HasIndex("UserId");

                    b.ToTable("Svadbe");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            BrojGostiju = 120,
                            BrojRata = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSvadbe = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DogovorenaCijena = 10000m,
                            Napomena = "Svadba održana u septembru, sve po dogovoru.",
                            PonudaId = 2,
                            Status = 3,
                            UserId = 6,
                            Vrijeme = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Id = 102,
                            BrojGostiju = 150,
                            BrojRata = 3,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSvadbe = new DateTime(2026, 10, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            DogovorenaCijena = 15000m,
                            Napomena = "Potvrđena rezervacija za oktobar.",
                            PonudaId = 1,
                            Status = 1,
                            UserId = 6,
                            Vrijeme = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 103,
                            BrojGostiju = 80,
                            BrojRata = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSvadbe = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DogovorenaCijena = 8500m,
                            Napomena = "Termin otkazan zbog promjene plana.",
                            PonudaId = 4,
                            Status = 2,
                            UserId = 6,
                            Vrijeme = new TimeSpan(0, 16, 30, 0, 0)
                        },
                        new
                        {
                            Id = 104,
                            BrojGostiju = 90,
                            BrojRata = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSvadbe = new DateTime(2025, 7, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            DogovorenaCijena = 7000m,
                            Napomena = "Tradicionalna svadba — zadovoljni narodnim ansamblom.",
                            PonudaId = 3,
                            Status = 3,
                            UserId = 9,
                            Vrijeme = new TimeSpan(0, 17, 0, 0, 0)
                        },
                        new
                        {
                            Id = 105,
                            BrojGostiju = 110,
                            BrojRata = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSvadbe = new DateTime(2025, 8, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            DogovorenaCijena = 10000m,
                            Napomena = "Elegantna večer uz gudače.",
                            PonudaId = 2,
                            Status = 3,
                            UserId = 10,
                            Vrijeme = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = 106,
                            BrojGostiju = 100,
                            BrojRata = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSvadbe = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DogovorenaCijena = 8500m,
                            Napomena = "Zabavna večer uz pop/rock bend.",
                            PonudaId = 4,
                            Status = 3,
                            UserId = 11,
                            Vrijeme = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            Id = 107,
                            BrojGostiju = 160,
                            BrojRata = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            DatumSvadbe = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            DogovorenaCijena = 15000m,
                            Napomena = "Prethodna luksuzna svadba u porodici.",
                            PonudaId = 1,
                            Status = 3,
                            UserId = 11,
                            Vrijeme = new TimeSpan(0, 18, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "mobile@salon.local",
                            FirstName = "Dalila",
                            IsActive = true,
                            LastName = "Korisnik",
                            PasswordHash = "N5b4vpOtGo4txmR/IoPFNoRg1kY=",
                            PasswordSalt = "JopMnUSdt7Cec4gKUV0rag==",
                            Username = "mobile"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "zaposlenik@salon.local",
                            FirstName = "Zaposlenik",
                            IsActive = true,
                            LastName = "Salon",
                            PasswordHash = "xObgsmDrWZgNlmGJsdxoRS+V/AE=",
                            PasswordSalt = "0k57QETJENx5BkJuK4wtZg==",
                            Username = "zaposlenik"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@salon.local",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "Korisnik",
                            PasswordHash = "qU2ck45AOJU9W8CVxAO89FyOb8M=",
                            PasswordSalt = "65z57pEcbOuw+c9Ma3X10Q==",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ana.popovic@salon.local",
                            FirstName = "Ana",
                            IsActive = true,
                            LastName = "Popović",
                            PasswordHash = "N5b4vpOtGo4txmR/IoPFNoRg1kY=",
                            PasswordSalt = "JopMnUSdt7Cec4gKUV0rag==",
                            Username = "ana.popovic"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "marko.softic@salon.local",
                            FirstName = "Marko",
                            IsActive = true,
                            LastName = "Softić",
                            PasswordHash = "N5b4vpOtGo4txmR/IoPFNoRg1kY=",
                            PasswordSalt = "JopMnUSdt7Cec4gKUV0rag==",
                            Username = "marko.softic"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ena.kovac@salon.local",
                            FirstName = "Ena",
                            IsActive = true,
                            LastName = "Kovač",
                            PasswordHash = "N5b4vpOtGo4txmR/IoPFNoRg1kY=",
                            PasswordSalt = "JopMnUSdt7Cec4gKUV0rag==",
                            Username = "ena.kovac"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAssigned")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 1,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            DateAssigned = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            RoleId = 2,
                            UserId = 11
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.UserZanr", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ZanrId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ZanrId");

                    b.HasIndex("ZanrId");

                    b.ToTable("UserZanrovi");

                    b.HasData(
                        new
                        {
                            UserId = 6,
                            ZanrId = 1
                        },
                        new
                        {
                            UserId = 6,
                            ZanrId = 9
                        },
                        new
                        {
                            UserId = 9,
                            ZanrId = 6
                        },
                        new
                        {
                            UserId = 9,
                            ZanrId = 7
                        },
                        new
                        {
                            UserId = 10,
                            ZanrId = 5
                        },
                        new
                        {
                            UserId = 10,
                            ZanrId = 4
                        },
                        new
                        {
                            UserId = 11,
                            ZanrId = 1
                        },
                        new
                        {
                            UserId = 11,
                            ZanrId = 2
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Zanr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Zanrovi");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Pop"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Rock"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Naziv = "Balet"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Jazz"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Klasična"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Narodna"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Starogradska"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Akustična"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Naziv = "Evergreen"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = false,
                            Naziv = "Elektronska"
                        });
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DekoracijaPonuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Dekoracija", "Dekoracija")
                        .WithMany("DekoracijePonuda")
                        .HasForeignKey("DekoracijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany("DekoracijePonuda")
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dekoracija");

                    b.Navigation("Ponuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.DnevniSastanak", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "StatusChangedByUser")
                        .WithMany()
                        .HasForeignKey("StatusChangedByUserId");

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("StatusChangedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MeniArtikal", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Artikal", "Artikal")
                        .WithMany("MeniArtikli")
                        .HasForeignKey("ArtikalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Meni", "Meni")
                        .WithMany("MeniArtikli")
                        .HasForeignKey("MeniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artikal");

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarPonuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Muzicar", "Muzicar")
                        .WithMany("MuzicariPonuda")
                        .HasForeignKey("MuzicarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany("MuzicariPonuda")
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muzicar");

                    b.Navigation("Ponuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.MuzicarZanr", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Muzicar", "Muzicar")
                        .WithMany("MuzicarZanrovi")
                        .HasForeignKey("MuzicarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Zanr", "Zanr")
                        .WithMany("MuzicarZanrovi")
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muzicar");

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Notifikacija", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.PasswordResetToken", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Ponuda", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Meni", "Meni")
                        .WithMany("Ponude")
                        .HasForeignKey("MeniId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Meni");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Racun", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "KreiraoUser")
                        .WithMany()
                        .HasForeignKey("KreiraoUserId");

                    b.HasOne("SvadbeniSalon.Services.Database.Svadba", "Svadba")
                        .WithMany("Racuni")
                        .HasForeignKey("SvadbaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KreiraoUser");

                    b.Navigation("Svadba");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Rata", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Svadba", "Svadba")
                        .WithMany("Rate")
                        .HasForeignKey("SvadbaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Svadba");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Recenzija", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany()
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Svadba", "Svadba")
                        .WithMany()
                        .HasForeignKey("SvadbaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ponuda");

                    b.Navigation("Svadba");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.RefreshToken", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Svadba", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Ponuda", "Ponuda")
                        .WithMany()
                        .HasForeignKey("PonudaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.User", "StatusChangedByUser")
                        .WithMany()
                        .HasForeignKey("StatusChangedByUserId");

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ponuda");

                    b.Navigation("StatusChangedByUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.UserRole", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.UserZanr", b =>
                {
                    b.HasOne("SvadbeniSalon.Services.Database.User", "User")
                        .WithMany("UserZanrovi")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SvadbeniSalon.Services.Database.Zanr", "Zanr")
                        .WithMany("UserZanrovi")
                        .HasForeignKey("ZanrId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Zanr");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Artikal", b =>
                {
                    b.Navigation("MeniArtikli");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Dekoracija", b =>
                {
                    b.Navigation("DekoracijePonuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Meni", b =>
                {
                    b.Navigation("MeniArtikli");

                    b.Navigation("Ponude");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Muzicar", b =>
                {
                    b.Navigation("MuzicarZanrovi");

                    b.Navigation("MuzicariPonuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Ponuda", b =>
                {
                    b.Navigation("DekoracijePonuda");

                    b.Navigation("MuzicariPonuda");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Svadba", b =>
                {
                    b.Navigation("Racuni");

                    b.Navigation("Rate");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.User", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");

                    b.Navigation("UserZanrovi");
                });

            modelBuilder.Entity("SvadbeniSalon.Services.Database.Zanr", b =>
                {
                    b.Navigation("MuzicarZanrovi");

                    b.Navigation("UserZanrovi");
                });
#pragma warning restore 612, 618
        }
    }
}
